name: washing
description: Washing application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  http: ^0.12.0+4
  provider: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


  assets:
    - assets/images/



  fonts:
    - family: Museo Sans Cyrl
      fonts:
        - asset: assets/fonts/MuseoSansCyrl-300.ttf
          weight: 300
        - asset: assets/fonts/MuseoSansCyrl-500.ttf
          weight: 500
        - asset: assets/fonts/MuseoSansCyrl-700.ttf
          weight: 700
